Cuda available: True
model_sample: 0
Cuda available: True
model_sample: 0
Cuda available: True
model_sample: 0
Model Loaded
Model Loaded
Model Loaded
input_sample: 0
input_sample: 0
input_sample: 0
Traceback (most recent call last):
Traceback (most recent call last):
  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/eval_model_trained.py", line 284, in <module>
  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/eval_model_trained.py", line 284, in <module>
Traceback (most recent call last):
  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/eval_model_trained.py", line 284, in <module>
            fig_err_vs_L(USE_CUDA = True,s = s)fig_err_vs_L(USE_CUDA = True,s = s)fig_err_vs_L(USE_CUDA = True,s = s)

  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/eval_model_trained.py", line 140, in fig_err_vs_L

  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/eval_model_trained.py", line 140, in fig_err_vs_L
  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/eval_model_trained.py", line 140, in fig_err_vs_L
    layers_true = model(input_true, invasive = True, USE_CUDA = USE_CUDA)    
      File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
layers_true = model(input_true, invasive = True, USE_CUDA = USE_CUDA)layers_true = model(input_true, invasive = True, USE_CUDA = USE_CUDA)

  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
        return forward_call(*input, **kwargs)    return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)


  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/../models/func_to_func2d_invasive.py", line 98, in forward
  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/../models/func_to_func2d_invasive.py", line 98, in forward
  File "/central/groups/astuart/mtrautne/BoundFNO/analysis/../models/func_to_func2d_invasive.py", line 98, in forward
        x = self.fc0(x)    x = self.fc0(x)

  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
x = self.fc0(x)
  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
            return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)

  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward

  File "/home/mtrautne/miniconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
            return F.linear(input, self.weight, self.bias)return F.linear(input, self.weight, self.bias)return F.linear(input, self.weight, self.bias)


RuntimeErrorRuntimeError: : mat1 and mat2 shapes cannot be multiplied (262144x3 and 5x64)RuntimeErrormat1 and mat2 shapes cannot be multiplied (262144x3 and 5x64): 
mat1 and mat2 shapes cannot be multiplied (262144x3 and 5x64)

